apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: capacitor
  namespace: flux-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - capacitor.atlas.stoinski.pro
      secretName: capacitor.atlas.stoinski.pro-keyandcert
  rules:
    - host: capacitor.atlas.stoinski.pro
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: capacitor
                port:
                  number: 9000
