apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: smb-storage
          mountPath: /mnt/smb-storage
        - name: nfs-storage
          mountPath: /mnt/nfs-storage
      volumes:
      - name: smb-storage
        persistentVolumeClaim:
          claimName: ubuntu-smb-storage
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: ubuntu-nfs-storage
