apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-rclone
  namespace: sftp-csi-driver
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: csi-rclone
  path: ./deploy/kubernetes/1.29
  prune: true
  wait: true
