apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ovh-webhook-fault
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - myappname.developer.myappname.dev
      secretName: myappname.developer.myappname.dev-keyandcert
  rules:
    - host: myappname.developer.myappname.dev
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: nothing
                port:
                  number: 8080
